### ISSUE TITLE
Implement best_attribute

### ISSUE THREAD

**Issue by za419** [alanwoj16/ps2#2]

**Comment by RyanWalkerChilton** [comment]
Alright, got a version of it. Need to test it, but also need sleep. I'll take a look when I wake up, but if one of you has time to add tests before then- this was a brain-burner.

**Comment by RyanWalkerChilton** [comment]
Current version should be good? To be perfectly honest, not 100% understanding update's requirements

**Comment by za419** [comment]
If you think it's good, go ahead and open a PR. We can fix it later if it breaks

**Comment by alanwoj16** [comment]
should be good. testID3AndEvaluate() and testID3AndTest() pass

**Comment by za419** [comment]
Fixed at some point before 444583f53ebcd34f3f2308166a4375a11b6a4ea2
